server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:2005/myfitpet
    username: postgres
    password: 050729
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: never

app:
  jwt:
    secret: "mySecretKeyForJWTTokenGenerationInSpringBootApplication2024"
    expiration: 86400000

pose:
  api:
    base-url: http://localhost:5001

chat:
  api:
    base-url: http://222.201.134.236:8000